# cert-manager Application
{{- if .Values.platformApps.certManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    {{- include "apps.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.spec.project }}
  
  source:
    repoURL: {{ .Values.platformApps.certManager.repoURL }}
    targetRevision: {{ .Values.platformApps.certManager.targetRevision }}
    chart: {{ .Values.platformApps.certManager.chart }}
    helm:
      valuesObject:
        {{- toYaml .Values.platformApps.certManager.values | nindent 8 }}
  
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.platformApps.certManager.namespace }}
  
  syncPolicy:
    {{- include "apps.syncPolicy" . | nindent 4 }}
{{- end }}
