{{- if .Values.platformApps.externalSecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    {{- include "apps.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ .Values.spec.project }}
  
  source:
    repoURL: {{ .Values.platformApps.externalSecrets.repoURL }}
    targetRevision: {{ .Values.platformApps.externalSecrets.targetRevision }}
    chart: {{ .Values.platformApps.externalSecrets.chart }}
    helm:
      valuesObject:
        {{- toYaml .Values.platformApps.externalSecrets.values | nindent 8 }}
  
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.platformApps.externalSecrets.namespace }}
  
  syncPolicy:
    {{- include "apps.syncPolicy" . | nindent 4 }}
{{- end }}
